spring:
    application:
        name: JHauzzer
    datasource:
        url: jdbc:mysql://localhost:3306/jhauzzer_data?allowPublicKeyRetrieval=true&useSSL=false
        username: root
        password: password
    security:
        user:
            name: admin
            password: admin

    jpa:
        generate-ddl: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect # Was MySQL8Dialect
        show-sql: true
    jps:
        hibernate:
            ddl:
                auto: update
    liquibase:
        change-log: classpath:db/changelog/main-changelog.xml